### PR TITLE
Migrate pitch to profile

### PR DESCRIPTION
**Pull request by verdefred**
## Summary

- Migrate pitch to profile
- Add rescue errors on update endpoints
- Add specs for update endpoints

### CODE REVIEW

**Review by RubenSousaDinis — COMMENTED** [review]
What about bio?

**Comment by verdefred** [comment]
> What about bio?

It's the "headline"

**Comment by RubenSousaDinis** [comment]
> > What about bio?
> 
> It's the "headline"

but it will stay in the `career_goal` model?

**Comment by verdefred** [comment]
> > > What about bio?
> > 
> > 
> > It's the "headline"
> 
> but it will stay in the `career_goal` model?

No. It's in the "profile", inside the talent. As the about

**Review by RubenSousaDinis — APPROVED** [review]

**Review by RubenSousaDinis — APPROVED** [review]

**Pull request merged**
