### PR TITLE
feat: invite used notification

### PR DESCRIPTION
**Pull request by shirleyodeng**
## Summary

This PR creates a notification and sends an email to the inviter when an invite is used to sign up by an invitee.

Screenshot 2022-08-13 at 22 29 25

Screenshot 2022-08-13 at 22 53 31

## Notion link

https://talentprotocol.notion.site/Referral-notification-a6faf0a92d44477590446ede14c01fc1

## How to test?

1. Sign up with using an invite code
2. The invite's user should receive an email and notification that someone's signed up using their invite

### CODE REVIEW

**Comment by shirleyodeng** [comment]
@RubenSousaDinis, a few things I weren't sure about so let me know if you need them changed;
- the copy on the email and email subject
- the copy and icon for the notification

**Review by RubenSousaDinis — COMMENTED** [review]
Great job! Only think missing: https://github.com/talentprotocol/web-dapp/blob/6d4509eff995c5fdef039964bb31c5bf56c2b6b4/test/mailers/previews/user_mailer_preview.rb#L2. Add the email preview to the preview class

**Comment by shirleyodeng** [comment]
> Great job! Only think missing:
> 
> https://github.com/talentprotocol/web-dapp/blob/6d4509eff995c5fdef039964bb31c5bf56c2b6b4/test/mailers/previews/user_mailer_preview.rb#L2
> 
> . Add the email preview to the preview class

Added 😁

**Review by RubenSousaDinis — COMMENTED** [review]
Well done!

**Pull request merged**
